package DataDictionaryLanguage.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import DataDictionaryLanguage.behavior.StructureDefinition__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class node_factories_Field {
  public static class NodeFactory_569590123104611885 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SNode nodeSd = SNodeOperations.getNodeAncestor(enclosingNode, CONCEPTS.StructureDefinition$$$, false, false);
      SPropertyOperations.assign(newNode, PROPS.name$MnvL, "Field-" + ((int) StructureDefinition__BehaviorDescriptor.getFieldCount_idvB_NbVejpE.invoke(nodeSd) + 1));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StructureDefinition$$$ = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732faaeb5dcL, "DataDictionaryLanguage.structure.StructureDefinition");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
