package DataDictionaryLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Operations extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Operations() {
    super(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0xf46f562b0b34895L, "Operations", "r:13ff4c76-a52d-486f-b493-09a1113f29c7(DataDictionaryLanguage.structure)/1100836963158804629");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Less_0 = new EnumerationDescriptor.MemberDescriptor("Less", "<", 0xf46f562b0b34896L, "r:13ff4c76-a52d-486f-b493-09a1113f29c7(DataDictionaryLanguage.structure)/1100836963158804630");
  private final EnumerationDescriptor.MemberDescriptor myMember_LessEqual_0 = new EnumerationDescriptor.MemberDescriptor("LessEqual", "<=", 0xf46f562b0b34897L, "r:13ff4c76-a52d-486f-b493-09a1113f29c7(DataDictionaryLanguage.structure)/1100836963158804631");
  private final EnumerationDescriptor.MemberDescriptor myMember_Equal_0 = new EnumerationDescriptor.MemberDescriptor("Equal", "=", 0xf46f562b0b3489aL, "r:13ff4c76-a52d-486f-b493-09a1113f29c7(DataDictionaryLanguage.structure)/1100836963158804634");
  private final EnumerationDescriptor.MemberDescriptor myMember_Greater_0 = new EnumerationDescriptor.MemberDescriptor("Greater", ">", 0xf46f562b0b348a3L, "r:13ff4c76-a52d-486f-b493-09a1113f29c7(DataDictionaryLanguage.structure)/1100836963158804643");
  private final EnumerationDescriptor.MemberDescriptor myMember_GreaterEqual_0 = new EnumerationDescriptor.MemberDescriptor("GreaterEqual", ">=", 0xf46f562b0b3489eL, "r:13ff4c76-a52d-486f-b493-09a1113f29c7(DataDictionaryLanguage.structure)/1100836963158804638");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0xf46f562b0b34895L, 0xf46f562b0b34896L, 0xf46f562b0b34897L, 0xf46f562b0b3489aL, 0xf46f562b0b348a3L, 0xf46f562b0b3489eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Less_0, myMember_LessEqual_0, myMember_Equal_0, myMember_Greater_0, myMember_GreaterEqual_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Less":
        return myMember_Less_0;
      case "LessEqual":
        return myMember_LessEqual_0;
      case "Equal":
        return myMember_Equal_0;
      case "Greater":
        return myMember_Greater_0;
      case "GreaterEqual":
        return myMember_GreaterEqual_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
