package DataDictionaryLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Aggregation_Constraints extends BaseConstraintsDescriptor {
  public Aggregation_Constraints() {
    super(CONCEPTS.Aggregation$H2);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Aggregation$H2 = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732faab6c5eL, "DataDictionaryLanguage.structure.Aggregation");
  }
}
