package DataDictionaryLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.errors.BaseQuickFixProvider;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_BetweenConstraint_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_BetweenConstraint_NonTypesystemRule() {
  }
  public void applyRule(final SNode betweenConstraint, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SPropertyOperations.getInteger(betweenConstraint, PROPS.number1$wI22) > SPropertyOperations.getInteger(betweenConstraint, PROPS.number2$wIw4)) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(betweenConstraint, "First number must be less then second.", "r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "1100836963157825802", null, errorTarget);
        {
          BaseQuickFixProvider intentionProvider = new BaseQuickFixProvider("DataDictionaryLanguage.typesystem.quickFixSwitchPlaces_QuickFix", "1100836963158163946", false);
          intentionProvider.putArgument("b", betweenConstraint);
          _reporter_2309309498.addIntentionProvider(intentionProvider);
        }
      }
    }

  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.BetweenConstraint$sS;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty number2$wIw4 = MetaAdapterFactory.getProperty(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0xf46f562b0a40303L, 0xf46f562b0a40306L, "number2");
    /*package*/ static final SProperty number1$wI22 = MetaAdapterFactory.getProperty(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0xf46f562b0a40303L, 0xf46f562b0a40304L, "number1");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BetweenConstraint$sS = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0xf46f562b0a40303L, "DataDictionaryLanguage.structure.BetweenConstraint");
  }
}
