package DataDictionaryLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_DataDictionary_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_DataDictionary_NonTypesystemRule() {
  }
  public void applyRule(final SNode dataDictionary, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (isEmptyString(SPropertyOperations.getString(dataDictionary, PROPS.name$MnvL))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(dataDictionary, "Data Dictionary must have name", "r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "569590123103574383", null, errorTarget);
      }
    }
    if (ListSequence.fromList(SLinkOperations.getChildren(dataDictionary, LINKS.predefinedDomains$NVdZ)).isEmpty()) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(dataDictionary, "You must define predefined domains", "r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "569590123103612177", null, errorTarget);
      }
    }
    for (SNode pDomain : SLinkOperations.getChildren(dataDictionary, LINKS.predefinedDomains$NVdZ)) {
      SNode current = pDomain;
      String instance = null;
      if (SNodeOperations.isInstanceOf(current, CONCEPTS.Boolean$8W)) {
        instance = "Boolean";
      }
      if (SNodeOperations.isInstanceOf(current, CONCEPTS.Text$RE)) {
        instance = "Text";
      }
      if (SNodeOperations.isInstanceOf(current, CONCEPTS.Date$_2)) {
        instance = "Date";
      }
      if (SNodeOperations.isInstanceOf(current, CONCEPTS.Double$mw)) {
        instance = "Double";
      }
      if (SNodeOperations.isInstanceOf(current, CONCEPTS.Integer$_x)) {
        instance = "Integer";
      }
      for (SNode node : SLinkOperations.getChildren(dataDictionary, LINKS.predefinedDomains$NVdZ)) {
        if (node != current) {
          if (SNodeOperations.isInstanceOf(node, CONCEPTS.Boolean$8W) && instance == "Boolean") {
            {
              final MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(node, "Duplicate boolean domains", "r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "569590123103874682", null, errorTarget);
            }
          }
          if (SNodeOperations.isInstanceOf(node, CONCEPTS.Text$RE) && instance == "Text") {
            {
              final MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(node, "Duplicate text domains", "r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "569590123103875363", null, errorTarget);
            }
          }
          if (SNodeOperations.isInstanceOf(node, CONCEPTS.Double$mw) && instance == "Double") {
            {
              final MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(node, "Duplicate double domains", "r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "569590123103879730", null, errorTarget);
            }
          }
          if (SNodeOperations.isInstanceOf(node, CONCEPTS.Integer$_x) && instance == "Integer") {
            {
              final MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(node, "Duplicate integer domains", "r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "569590123103880595", null, errorTarget);
            }
          }
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.DataDictionary$2d;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static boolean isEmptyString(String str) {
    return str == null || str.isEmpty();
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink predefinedDomains$NVdZ = MetaAdapterFactory.getContainmentLink(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x6d04cb7a96e885ffL, 0x7e79732faad5e05L, "predefinedDomains");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Boolean$8W = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732fa9d91b5L, "DataDictionaryLanguage.structure.Boolean");
    /*package*/ static final SConcept Text$RE = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732fa9d42adL, "DataDictionaryLanguage.structure.Text");
    /*package*/ static final SConcept Date$_2 = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732fa9d91c5L, "DataDictionaryLanguage.structure.Date");
    /*package*/ static final SConcept Double$mw = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732fa9d91bcL, "DataDictionaryLanguage.structure.Double");
    /*package*/ static final SConcept Integer$_x = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732fa9d91c6L, "DataDictionaryLanguage.structure.Integer");
    /*package*/ static final SConcept DataDictionary$2d = MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x6d04cb7a96e885ffL, "DataDictionaryLanguage.structure.DataDictionary");
  }
}
