package DataDictionaryLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class quickFixSwitchPlaces_QuickFix extends QuickFix_Runtime {
  public quickFixSwitchPlaces_QuickFix() {
    super(new SNodePointer("r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "1100836963158160633"));
  }
  public String getDescription(SNode node) {
    return "Switch places of first and second number";
  }
  public void execute(SNode node) {
    int number = SPropertyOperations.getInteger(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number1$wI22);
    SPropertyOperations.assign(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number1$wI22, SPropertyOperations.getInteger(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number2$wIw4));
    SPropertyOperations.assign(((SNode) quickFixSwitchPlaces_QuickFix.this.getField("b")[0]), PROPS.number2$wIw4, number);
  }

  private static final class PROPS {
    /*package*/ static final SProperty number1$wI22 = MetaAdapterFactory.getProperty(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0xf46f562b0a40303L, 0xf46f562b0a40304L, "number1");
    /*package*/ static final SProperty number2$wIw4 = MetaAdapterFactory.getProperty(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0xf46f562b0a40303L, 0xf46f562b0a40306L, "number2");
  }
}
