package DataDictionaryLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class quick_fix_min_one_element_QuickFix extends QuickFix_Runtime {
  public quick_fix_min_one_element_QuickFix() {
    super(new SNodePointer("r:84c8e41f-b64d-4d63-b9bb-c3c67b06045b(DataDictionaryLanguage.typesystem)", "569590123105414711"));
  }
  public String getDescription(SNode node) {
    return "Quick Fix automatically add field in empty structure";
  }
  public void execute(SNode node) {
    SNode field = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732fa9bc605L, "DataDictionaryLanguage.structure.Field"));
    SPropertyOperations.assign(field, PROPS.name$MnvL, "Field-1");
    ListSequence.fromList(SLinkOperations.getChildren(((SNode) quick_fix_min_one_element_QuickFix.this.getField("structure")[0]), LINKS.elements$GOFf)).addElement(field);
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink elements$GOFf = MetaAdapterFactory.getContainmentLink(0x83d7e20faa624554L, 0x9cc2d13247d6555eL, 0x7e79732fa9d91cdL, 0x7e79732fa9d91d0L, "elements");
  }
}
